apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
{{- range .Values.proxy.ports }}
    - name: http{{ .port }}
      port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodePort }}
{{- end }}